name: Cascading Permissions Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  first_approver:
    runs-on: ubuntu-latest
    steps:
      - name: First Approval
        run: echo "First approval completed"

  second_approver:
    runs-on: ubuntu-latest
    needs: first_approver
    steps:
      - name: Check for Second Approval
        id: check_approval
        run: |
          APPROVED=true  # Simulate approval; set to false if rejected
          if [ "$APPROVED" = true ]; then
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/SalmaaaTareeek/GithubActions-demo/environments/Hypercare/variables/SM_DM_APPROVED \
            -d '{"name":"SM_DM_APPROVED","value":"true"}'
          else
            curl -X PUT -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/SalmaaaTareeek/GithubActions-demo/environments/Hypercare/variables/SM_DM_APPROVED \
            -d '{"name":"SM_DM_APPROVED","value":"false"}'
          fi  # Close the if statement properly

  deploy:
    runs-on: ubuntu-latest
    needs: second_approver
    # if: ${{ env.SM_DM_APPROVED == 'true' }}
    steps:
      - name: Deployment Step
        run: echo "Deployment completed successfully"
