name: Cascading Permissions Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs: 
  first_approver:
    runs-on: ubuntu-latest
    environment:
      name: Hypercare
    steps:
      - run: echo "Waiting For Approval"

  second_approver:
    runs-on: ubuntu-latest
    needs: first_approver
    environment:
      name: Hypercare
    steps:
      - run: echo "Waiting for second Approval"

  deploy:
    runs-on: ubuntu-latest
    needs: second_approver
    steps:
      - run: echo "Done Approving"
