name: CI/CD Pipeline with Manual Approval

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run Tests
      run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment: production  # Use the environment that requires manual approval

    steps:
    - name: Deploy to Production
      run: echo "Deploying application to production..."
