name: Cascading Permissions Deployment

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs: 
  first_approver:
    runs-on: ubuntu-latest
    environment:
      name: Hypercare
    steps:
      # Set the environment variable
      - name: Set SM_DM_APPROVED
        run: echo "SM_DM_APPROVED" >> $GITHUB_ENV
      
      # This step runs only if SM_DM_APPROVED is 'false'
      - name: Approval Step
        if: env.SM_DM_APPROVED == 'false'
        run: echo "Waiting For Approval" , echo "SM_DM_APPROVED=true" >> $GITHUB_ENV
        # run: echo "SM_DM_APPROVED=true" >> $GITHUB_ENV

  second_approver:
    runs-on: ubuntu-latest
    needs: first_approver
    environment:
      name: Hypercare
    steps:
      - run: echo "Waiting for second Approval"

  deploy:
    runs-on: ubuntu-latest
    needs: second_approver
    steps:
      - run: echo "Done Approving"
