name: CI with Manual Approval

on:
  workflow_dispatch:  # Allows the workflow to be triggered manually

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run tests
      run: echo "Running tests..."

  manual_approval:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Awaiting manual approval
      run: echo "Please review the results and approve this step."
      if: ${{ github.event.inputs.approve == 'yes' }}

    - name: Proceed after approval
      run: echo "Approved. Proceeding to the next step..."